### ISSUE TITLE
Just an idea for making Esphome component to read/shiff from any BLE HID Server input 

### ISSUE THREAD

**Issue by ivanspirit** [fsievers22/esphome-ble-remote#9]
Hi fsievers22 and congrats for the great project! 
I'm not quite sure is this the right place for asking you a question but if it's not just tell me and I'll erase it from here.

My programmer skills are far away from yours and I'm trying to make an Esphome project aimed to reading from BLE HID device server input, just a raw data or whatever it is coming from  the device. Text sensor seemed to me as a good solution. What do you think how much harder would be to turn your project into the new Esphome project for input reading from BLE HID server device?
Thank and regards!

**Comment by fsievers22** [comment]
Hi ivanspirit, thanks for your interest!
It would certainly be possible to do that. I think instead of using a keymap in the `ESP_GATTC_NOTIFY_EVT` you would have to just publish the raw data to a the TextSensor.
Unfortunately I don't have the time or the possibilities to test that at the moment, so I can't help you any further.
